# Generated by Django 5.1.3 on 2024-11-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='descriptiins',
            new_name='description',
        ),
    ]
