# Generated by Django 5.1.3 on 2024-11-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='descriptions',
            new_name='description',
        ),
    ]
